[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
crowdfunding = "33uCBHj4K8icQcx37Q9QzWa77LvXYNWcoGDKx5T3JsZS"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/georgehigbie/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
